### ISSUE TITLE
Stylelint throws error

### ISSUE THREAD

**Issue by nileshgulia1** [eea/volto-slate#216]
Executing `stylelint` in a fresh slate project throws error:
```
TypeError: this.getPosition is not a function

    at LessParser.inlineComment (/opt/frontend/my-volto-project/node_modules/postcss-less/lib/LessParser.js:71:28)
    at LessParser.isInlineComment (/opt/frontend/my-volto-project/node_modules/postcss-less/lib/nodes/inline-comment.js:37:12)
    at LessParser.other (/opt/frontend/my-volto-project/node_modules/postcss-less/lib/LessParser.js:156:36)
    at LessParser.parse (/opt/frontend/my-volto-project/node_modules/postcss/lib/parser.js:77:16)
    at Object.parse (/opt/frontend/my-volto-project/node_modules/postcss-less/lib/index.js:11:12)
    at parser (/opt/frontend/my-volto-project/node_modules/postcss-syntax/parser.js:10:22)
    at Object.parse (/opt/frontend/my-volto-project/node_modules/postcss-syntax/parse.js:28:10)
    at new LazyResult (/opt/frontend/my-volto-project/node_modules/postcss/lib/lazy-result.js:60:16)
    at /opt/frontend/my-volto-project/node_modules/stylelint/lib/getPostcssResult.js:124:19
    at async Promise.all (index 1)

  ```

This is probably due to postcss-less requiring `postcss@8`.
Volto does have `postcss@8` but gets overridden by some dep which pulls postcss@7 in a new volto-project.
```
yarn why postcss
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "postcss"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "postcss@7.0.29"
info Has been hoisted to "postcss"
info Reasons this module exists
   - "workspace-aggregator-8d0ce0da-8652-476e-818e-661d35aa32dc" depends on it
   - Hoisted from "_project_#postcss-safe-parser#postcss"
   - Hoisted from "_project_#stylelint#postcss"
   - Hoisted from "_project_#@plone#volto#postcss-loader#postcss"
   - Hoisted from "_project_#stylelint#postcss-scss#postcss"
   - Hoisted from "_project_#stylelint#postcss-less#postcss"
   - Hoisted from "_project_#@plone#volto#postcss-overrides#postcss"
   - Hoisted from "_project_#stylelint-config-idiomatic-order#stylelint-order#postcss"
   - Hoisted from "_project_#stylelint#sugarss#postcss"
   - Hoisted from "_project_#stylelint#postcss-sass#postcss"
   - Hoisted from "_project_#@plone#volto#postcss-flexbugs-fixes#postcss"
   - Hoisted from "_project_#@plone#volto#autoprefixer#postcss"
   - Hoisted from "_project_#stylelint#postcss-reporter#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss"
   - Hoisted from "_project_#stylelint-config-idiomatic-order#stylelint-order#postcss-sorting#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#css-loader#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#css-loader#icss-utils#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-color-hex-alpha#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-custom-media#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#css-loader#postcss-modules-local-by-default#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-custom-properties#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-attribute-case-insensitive#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-color-functional-notation#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-color-mod-function#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-color-rebeccapurple#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-custom-selectors#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-dir-pseudo-class#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-env-function#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-focus-visible#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-focus-within#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-font-variant#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-gap-properties#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-image-set-function#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-initial#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-lab-function#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-logical#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-media-minmax#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-nesting#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-overflow-shorthand#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-page-break#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-place#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-pseudo-class-any-link#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-replace-overflow-wrap#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-selector-matches#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-selector-not#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#css-blank-pseudo#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#css-prefers-color-scheme#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-color-gray#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#postcss-double-position-gradients#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#css-loader#postcss-modules-extract-imports#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#postcss-preset-env#css-has-pseudo#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#css-loader#postcss-modules-scope#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#css-loader#postcss-modules-values#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#cssnano-util-raw-cache#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-colormin#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-convert-values#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-discard-comments#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-discard-duplicates#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-discard-empty#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-discard-overridden#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-merge-longhand#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-merge-rules#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-minify-font-values#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-minify-gradients#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-minify-params#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-minify-selectors#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-normalize-charset#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-normalize-display-values#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-normalize-positions#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-normalize-repeat-style#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-normalize-string#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-normalize-timing-functions#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-normalize-unicode#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-normalize-url#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-normalize-whitespace#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-ordered-values#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-reduce-initial#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-reduce-transforms#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-svgo#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-unique-selectors#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#css-declaration-sorter#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-calc#postcss"
   - Hoisted from "_project_#@plone#volto#razzle#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-merge-longhand#stylehacks#postcss"
info Disk size without dependencies: "1.13MB"
info Disk size with unique dependencies: "2.05MB"
info Disk size with transitive dependencies: "2.29MB"
info Number of shared dependencies: 8
=> Found "@plone/volto#postcss@8.3.11"
info This module exists because "_project_#@plone#volto" depends on it.
info Disk size without dependencies: "308KB"
info Disk size with unique dependencies: "1.24MB"
info Disk size with transitive dependencies: "1.24MB"
info Number of shared dependencies: 3
=> Found "@plone/volto#stylelint#postcss@8.4.5"
info This module exists because "_project_#@plone#volto#stylelint" depends on it.
info Disk size without dependencies: "340KB"
info Disk size with unique dependencies: "1.27MB"
info Disk size with transitive dependencies: "1.27MB"
info Number of shared dependencies: 3
✨  Done in 0.42s.
```

**Comment by nileshgulia1** [comment]
Fixed by https://github.com/plone/volto/pull/2945
